### ISSUE TITLE
support xdg base dir spec

### ISSUE THREAD

**Issue by rahulsundaram** [petems/tugboat#124]
Hi
According to XDG Base directory specification:

User data should go into $XDG_DATA_HOME (which default to ~/.local/share),
user preferences should go into $XDG_CONFIG_HOME (which default to ~/.config)
and cached data should go to $XDG_CACHE_HOME (which default to ~/.cache). 

References:

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

http://ploum.net/post/207-modify-your-application-to-use-xdg-folders

Ruby library for supporting the spec
https://rubygems.org/gems/xdg

**Comment by petems** [comment]
I would love to add this but I don't have the bandwidth right now. If someone wants to add it, feel free to PR

Right now, a workaround would be to set the environment variable like so: `TUGBOAT_CONFIG_PATH=~/.config/tugboat`
