### ISSUE TITLE
Commands like "droplets" need formatting switches

### ISSUE THREAD

**Issue by adamierymenko** [petems/tugboat#206]
Commands like "droplets" need formatting switches to do things like only list IPs to avoid stuff like:

```
tugboat droplets | grep -F TEST | cut -d : -f 2 | cut -d ' ' -f 2 | cut -d , -f 1 >>big-test-hosts
```

**Comment by petems** [comment]
Makes sense.

Hmm, this would probably be easiest by extending the porcelain mode from the info method into the droplets method.

```
$ tugboat info -n foo-node --porcelain --attribute=ip4
10.0.1.1
```

How would you like it to look when it outputs, something like this:

```
$ tugboat droplets --porcelain --attribute=ip4
foo-node, 10.0.1.1
```

**Comment by petems** [comment]
@adamierymenko Can you give an example of how you want it to look?

Do you want a CSV style output like we do for info and `--porcelain` mode:

```
$ tugboat droplets --porcelain --attribute=ip4
foo-node, 10.0.1.1
foo-node2, 10.0.1.2
```

**Comment by adamierymenko** [comment]
CSV would be fine, and ditch the extra spaces since it requires an extra 'cut' or 'sed' etc. from the command line. Goal is to make it easy to script stuff.

**Comment by petems** [comment]
Could also do an output format flag: csv, yaml or JSON :+1:

**Comment by petems** [comment]
@adamierymenko Are you still using tugboat? Bit late now (2 years!) but I finally got this working now:

```
$ tugboat droplets --attribute=ip4
test-blog-1,41.101.11.22
test-blog-2,138.68.11.22
```

Got it up as a PR here: https://github.com/petems/tugboat/pull/294

**Comment by petems** [comment]
@psobot Also liked this issue, are you interested in trying this? 

I've just merged this into master, any problems feel free to open a new issue or PR 👍
