### ISSUE TITLE
Insecure Storage Of Cache Files in petems/tugboat (master)

### ISSUE THREAD

**Issue by petems** [petems/tugboat#271]
# [Insecure Storage Of Cache Files in petems/tugboat (master)](https://petems.sourceclear.io/teams/000t7aj/issues/vulnerabilities/1848257/966994)

## Issue Details

- **Vulnerability**: Insecure Storage Of Cache Files
- **Severity**: Low
- **Project**: petems/tugboat
- **Branch**: master
- **Scan Date**: Jul 3, 2017 12:01:10

## Issue Decription
RuboCop does not store cache files securely. It stores the cache files in `\tmp`, where a malicious local user can tamper with cache files belonging to other users.

[View more details](https://petems.sourceclear.io/teams/000t7aj/issues/vulnerabilities/1848257/966994)

**Comment by attritionorg** [comment]
Base issue for reference: https://github.com/bbatsov/rubocop/issues/4336
