### ISSUE TITLE
snapshot not working

### ISSUE THREAD

**Issue by mxdpeep** [petems/tugboat#280]
$ tugboat snapshot xxx.gscloud.cz
Tugboat attempted to find a droplet with no arguments.
Try running `tugboat snapshot dropletname`
For more help run: `tugboat help snapshot`

**Comment by petems** [comment]
@mxdpeep snapshot requires the exact name or ID of a droplet (no fuzzy matching):

The help needs updating however:

```
Usage:
  tugboat snapshot SNAPSHOT_NAME FUZZY_NAME [OPTIONS]

Options:
  -i, [--id=ID]      # The ID of the droplet.
  -n, [--name=NAME]  # The exact name of the droplet
  -q, [--quiet]

Queue a snapshot of the droplet.
```
